Final_Project/Blog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProfile);
            return View(posts.ToList());
        }
        public ActionResult tracuu(String q="")
        {
            List<Post> posts = db.Posts.Where(p => p.Title.Contains(q)).ToList();
            return View(posts);
        }
        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            ViewData["idpost"] = id;
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post, string Content)
        {
            if (ModelState.IsValid)
            {
                post.DateCreated = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).
                    Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserID = userid;
                //Tao list các Tag
                List<Tag> Tags = new List<Tag>();
                //tach cac Tag theo dau ,
                string[] TagContent = Content.Split(',');
                //Lập các tag vừa tách
                foreach (string item in TagContent)
                {
                    //Tìm xem tag content đã có hay chưa
                    Tag TagExists = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        //nếu có tag rồi thì add thêm Post vào
                        TagExists = ListTag.First();
                        TagExists.Posts.Add(post);
                    }
                    else
                    {
                        //nếu chưa có tag thì tạo mới
                        TagExists = new Tag();
                        TagExists.Content = item;
                        TagExists.Posts = new List<Post>();
                        TagExists.Posts.Add(post);
                    }
                    //add vào List các tag
                    Tags.Add(TagExists);
                }
                //Gán List Tag cho Post
                post.Tags = Tags;
                post.Tags = Tags;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserID);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserID);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                post.DateCreated = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).
                    Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserID = userid;

                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserID);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Final_Project/Blog/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    public class QuestionController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Question/

        public ActionResult Index()
        {
            return View(db.Questions.ToList());
        }

        //
        // GET: /Question/Details/5

        public ActionResult Details(int id = 0)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // GET: /Question/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Question/Create

        [HttpPost]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(question);
        }

        //
        // GET: /Question/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Question/Edit/5

        [HttpPost]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        //
        // GET: /Question/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Question/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Final_Project/Blog/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    [Authorize]
    public class VideoController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Video/
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Videos.ToList());
        }

        //
        // GET: /Video/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Video video = db.Videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        //
        // GET: /Video/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Video/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Video video)
        {
            if (ModelState.IsValid)
            {
                db.Videos.Add(video);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(video);
        }

        //
        // GET: /Video/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Video video = db.Videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        //
        // POST: /Video/Edit/5

        [HttpPost]
        public ActionResult Edit(Video video)
        {
            if (ModelState.IsValid)
            {
                db.Entry(video).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(video);
        }

        //
        // GET: /Video/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Video video = db.Videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        //
        // POST: /Video/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Video video = db.Videos.Find(id);
            db.Videos.Remove(video);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Final_Project/Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    < <marquee  width="100%" height="50px" bgcolor="blue" direction="right">
            <font face="georgia" size="10" color="yellow"> Chào mừng đến với website chuabenhmatngu.org ! </font>
        </marquee>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <style>
        .searchform {
            float: right;
            margin-top: 0px;
            border: #00afdd 2px solid;
            height: 27px;
            width: 350px;
        }

            .searchform input[type=text] {
                width: 255px;
                height: 21px;
                border: 2px;
                background: #00afdd;
                float: left;
                margin: 0px;
                padding: 3px;
            }

            .searchform input[type=submit] {
                border: #00afdd 1px solid;
                float: right;
                margin: 0px 0px 0px 2px;
                height: 27px;
                padding-top: 0px;
                background: #00afdd;
            }
    </style>
    <body background="~/Images/90.jpg">
        <!DOCTYPE html>
        <html>
        <title>Search Box Example 1</title>
        <meta name="ROBOTS" content="NOINDEX, NOFOLLOW" />
        <!-- CSS styles for standard search box -->
        <style type="text/css">
            #tfheader {
                background-color: #c3dfef;
            }

            #tfnewsearch {
                float: right;
                padding: 20px;
            }

            .tftextinput {
                margin: 0;
                padding: 5px 15px;
                font-family: Arial, Helvetica, sans-serif;
                font-size: 14px;
                border: 1px solid #0076a3;
                border-right: 0px;
                border-top-left-radius: 5px 5px;
                border-bottom-left-radius: 5px 5px;
            }

            .tfbutton {
                margin: 0;
                padding: 5px 15px;
                font-family: Arial, Helvetica, sans-serif;
                font-size: 14px;
                outline: none;
                cursor: pointer;
                text-align: center;
                text-decoration: none;
                color: #ffffff;
                border: solid 1px #0076a3;
                border-right: 0px;
                background: #0095cd;
                background: -webkit-gradient(linear, left top, left bottom, from(#00adee), to(#0078a5));
                background: -moz-linear-gradient(top, #00adee, #0078a5);
                border-top-right-radius: 5px 5px;
                border-bottom-right-radius: 5px 5px;
            }

                .tfbutton:hover {
                    text-decoration: none;
                    background: #007ead;
                    background: -webkit-gradient(linear, left top, left bottom, from(#0095cc), to(#00678e));
                    background: -moz-linear-gradient(top, #0095cc, #00678e);
                }
                /* Fixes submit button height problem in Firefox */
                .tfbutton::-moz-focus-inner {
                    border: 0;
                }

            .tfclear {
                clear: both;
            }
        </style>
</head>

<body>
    <div id="tfheader" style="float: right">
        <form id="tfnewsearch" method="get" action="/Post/tracuu">
            <input type="text" class="tftextinput" name="q" size="21" maxlength="120">
            <input type="submit" value="search" class="tfbutton">
        </form>
        <div class="tfclear"></div>
    </div>
    <header>
        <div class="content-wrapper">

           
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section> <div class="float-left">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                        <li>@Html.ActionLink("Bài đăng", "Index", "Post")</li>
                        <li>@Html.ActionLink("Video giải trí", "Index", "Video")</li>
                        <li>@Html.ActionLink("Đặt câu hỏi", "Create", "Question")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year -Web chữa bệnh mất ngủ</p>
            </div>
        </div>
    </footer>


    @RenderSection("scripts", required: false)
    <script type="text/javascript" src="http://itexpressvn.com/js/noel.js"></script>
    <!-- End Code CongTu9xYk-YkWaP.wAp.sH --><script type="text/javascript" src="http://ykwap.wap.sh/code/xtgem/js/Noel/snow_2.js"></script><!-- End Code CongTu9xYk-YkWaP.wAp.sH -->
   
</body>
</html>
<div class="float-left">
    Đang Online
            <br />
    <script id="_wauxr8">
        var _wau = _wau || []; _wau.push(["classic", "u7d326xooqw9", "xr8"]);
        (function () {
            var s = document.createElement("script"); s.async = true;
            s.src = "http://widgets.amung.us/classic.js";
            document.getElementsByTagName("head")[0].appendChild(s);
        })();

    </script>

</div>
<div class="float-right">
    Số người truy cập
            <br />
    <script id="_wauxsa">var _wau = _wau || []; _wau.push(["classic", "o9jetwpot0gg", "xsa"]);
        (function () {
            var s = document.createElement("script"); s.async = true;
            s.src = "http://widgets.amung.us/classic.js";
            document.getElementsByTagName("head")[0].appendChild(s);
        })();</script>

</div>